# Example usage:

# application:
#   compress: false
#   output: "application.js"
#   files: 
#     - "application/Application.Data.js"
#     - "application/Application.Controller.js"
#     - "application/Application.Interface.js"
# 
# jquery:
#   compress: true
#   output: "jquery.plugins.js"
#   files:
#     - "jquery/plugins/jquery.cookie.js"
#     - "jquery/plugins/jquery.cycle.all.min.js"
#     - "jquery/plugins/jquery.query.js"